# frozen_string_literal: true

source "https://rubygems.org"

gem "puma"
gem "rackup"
gem "sinatra"

group :development, :test do
  gem "rake"
  gem "rubocop", require: false
end

group :test do
  gem "rack-test"
  gem "rspec"
end
